name: build locally

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node-20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: latest
      - run: | 
          echo "build process started"
      - run: npm ci
      - run: | 
          echo "install complete"
      - run: npm run build
      - run: | 
          echo "build success"
